---
# Define Content Views that contain custom Products
sat_content_views_custom_products:
  - name: 'cv-elastic-elastic-el-8'
    repositories:
      - name: 'repo-elastic-elastic-8-el-8'
        product: 'prd-elastic-elastic'

  - name: 'cv-zabbix-zabbix-rhel-8'
    repositories:
      - name: 'repo-zabbix-zabbix-6_0-rhel-8'
        product: 'prd-zabbix-zabbix'

  - name: 'cv-zabbix-zabbix-rhel-9'
    repositories:
      - name: 'repo-zabbix-zabbix-6_0-rhel-9'
        product: 'prd-zabbix-zabbix'
